### ISSUE TITLE
ImportError: cannot import name 'string_concat', which makes python3 manage.py check fails

### ISSUE THREAD

**Issue by Panlichen** [adamchainz/django-mysql#418]
Maybe there are some version conflicts. Here's the trace code:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/Django-2.1.dev20171128075237-py3.6.egg/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/Django-2.1.dev20171128075237-py3.6.egg/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/Django-2.1.dev20171128075237-py3.6.egg/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/Django-2.1.dev20171128075237-py3.6.egg/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.6/site-packages/Django-2.1.dev20171128075237-py3.6.egg/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/django_mysql/models/__init__.py", line 16, in <module>
    from django_mysql.models.fields import (  # noqa
  File "/usr/local/lib/python3.6/site-packages/django_mysql/models/fields/__init__.py", line 11, in <module>
    from django_mysql.models.fields.json import JSONField  # noqa
  File "/usr/local/lib/python3.6/site-packages/django_mysql/models/fields/json.py", line 14, in <module>
    from django_mysql import forms
  **_File "/usr/local/lib/python3.6/site-packages/django_mysql/forms.py", line 14, in <module>
    from django.utils.translation import string_concat
ImportError: cannot import name 'string_concat'_**

*If this is a bug, please fill in the below, else delete*

Django Version: Django 2.1

Database and version used: MySQL 5.7.20

Version: install Django-MySQL with pip3 just now, I don't know exactly which version it is.

**Comment by adamchainz** [comment]
Django 2.1 is the current Django master, Django-MySQL doesn't support it. I'll upgrade to support it once its alpha is out. Please only use stable Django versions!
