### ISSUE TITLE
"ValueError: Tried to release an unheld lock" with a retried connection

### ISSUE THREAD

**Issue by stevejalim** [adamchainz/django-mysql#560]
Summary:

When using django-mysql with https://github.com/jd/tenacity to handle dropped connections, we're sometimes hitting the following issue when the DB connection goes away and is replaced by `tenacity`:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/src/app/REDACTED/plusers/management/commands/REDACTED_report.py", line 131, in handle
    logger.info("All done - releasing lock")
  File "/usr/local/lib/python3.7/site-packages/django_mysql/locks.py", line 43, in __exit__
    self.release()
  File "/usr/local/lib/python3.7/site-packages/django_mysql/locks.py", line 66, in release
    raise ValueError("Tried to release an unheld lock.")
ValueError: Tried to release an unheld lock.```
```

I can replicate it locally by killing the connection from inside mysql while the reporting util is running. The reporting code picks up with a new connection, but then we get the lock error.

I appreciate this falls into that awkward valley of two separate projects doing things, but from django-mysql's point of view is there anything we can do (eg config?) to keep django-mysql's Lock behaviour happy even if we're having to replace connections during a Lock? 

Thanks very much!
Steve

Django Version: 2.2

Database and version used: MySQL 5.7

Version: 3.0.0.post1

**Comment by adamchainz** [comment]
MySQL/MariaDB locks are per connection, you can't hold them if you close your connection. In general it's not safe to reconnect in the middle of some process - connections are stateful. You'll lose transactions, transaction locks, user variables, settings, etc.

Probably you want to wrap tenacity around some top-level process (such as a request, queued task, management command...) rather than some function deep in the call chain.
