### ISSUE TITLE
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'> with Smart Iterator

### ISSUE THREAD

**Issue by gabn88** [adamchainz/django-mysql#657]
Summary: Smart iterator on an ssh session with an external server and shell_plus using bpython and report_process=True gives RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>

Django Version: 2.2.10, python 3.7.7

Database and version used: not important

Version: django-mysql 3.4.0

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/django_extensions/management/commands/shell_plus.py", line 117, in run_from_argv
    return super(Command, self).run_from_argv(argv)
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/django_extensions/management/commands/shell_plus.py", line 551, in handle
    shell()
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/django_extensions/management/commands/shell_plus.py", line 311, in run_bpython
    embed(imported_objects, **kwargs)
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/bpython/__init__.py", line 41, in embed
    return main(args, locals_, banner)
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/bpython/curtsies.py", line 191, in main
    exit_value = repl.mainloop(True, paste)
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/bpython/curtsies.py", line 123, in mainloop
    self.process_event_and_paint(e)
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/bpython/curtsies.py", line 101, in process_event_and_paint
    scrolled = self.window.render_to_terminal(array, cursor_pos)
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/curtsies/window.py", line 431, in render_to_terminal
    self.scroll_down()
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/curtsies/window.py", line 40, in scroll_down
    self.write(SCROLL_DOWN)  # TODO will blessings do this?
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/curtsies/window.py", line 44, in write
    self.out_stream.flush()
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/bpython/curtsiesfrontend/repl.py", line 563, in sigwinch_handler
    cursor_dy = self.get_cursor_vertical_diff()
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/bpython/curtsies.py", line 72, in get_cursor_vertical_diff
    return self.window.get_cursor_vertical_diff()
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/curtsies/window.py", line 344, in get_cursor_vertical_diff
    cursor_dy += self._get_cursor_vertical_diff_once()
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/curtsies/window.py", line 352, in _get_cursor_vertical_diff_once
    row, col = self.get_cursor_position()
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/curtsies/window.py", line 279, in get_cursor_position
    self.write(query_cursor_position)
  File "/home/gabn88/webapps/test_production_v6/lib/python3.7/site-packages/curtsies/window.py", line 44, in write
    self.out_stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>
```

It only happens after a minute or so.

**Comment by adamchainz** [comment]
That looks like a bug in bpython to me. Please report the bug there.

I'd recommend using ipython instead.

**Comment by adamchainz** [comment]
It could be `SmartIterator`'s report using the `\r` character that has broken it.

**Comment by gabn88** [comment]
Switching to ipython solved the issue :)
