### ISSUE TITLE
Django 1.7.7 Test

### ISSUE THREAD

**Issue by alexsilva** [adamchainz/django-mysql#68]
Whenever I try to run the django test (on windows) I see this error

```
ImportError: No module named aggregation_regress.tests
```

Occurs from that module code snippet sqlserver_ado:

```
    def create_test_db(self, *args, **kwargs):
        self.mark_tests_as_expected_failure(self.connection.features.failing_tests)
        super(DatabaseCreation, self).create_test_db(*args, **kwargs)
```

For what reason 'sqlserver_ado' module to import something that is not within the django?

https://github.com/django/django/tree/master/tests/aggregation_regress

Full stack:
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 4.0.6\helpers\pycharm\django_test_manage.py", line 129, in <module>
    utility.execute()
  File "C:\Program Files (x86)\JetBrains\PyCharm 4.0.6\helpers\pycharm\django_test_manage.py", line 104, in execute
    PycharmTestCommand().run_from_argv(self.argv)
  File "project-path\core_packages\django\core\management\commands\test.py", line 50, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "project-path\core_packages\django\core\management\base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "project-path\core_packages\django\core\management\commands\test.py", line 71, in execute
    super(Command, self).execute(*args, **options)
  File "project-path\core_packages\django\core\management\base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "C:\Program Files (x86)\JetBrains\PyCharm 4.0.6\helpers\pycharm\django_test_manage.py", line 91, in handle
    failures = TestRunner(test_labels, verbosity=verbosity, interactive=interactive, failfast=failfast, keepdb='--keepdb' in sys.argv)
  File "C:\Program Files (x86)\JetBrains\PyCharm 4.0.6\helpers\pycharm\django_test_runner.py", line 232, in run_tests
    extra_tests=extra_tests, **options)
  File "C:\Program Files (x86)\JetBrains\PyCharm 4.0.6\helpers\pycharm\django_test_runner.py", line 132, in run_tests
    return super(DjangoTeamcityTestRunner, self).run_tests(test_labels, extra_tests, **kwargs)
  File "project-path\core_packages\django\test\runner.py", line 147, in run_tests
    old_config = self.setup_databases()
  File "project-path\core_packages\django\test\runner.py", line 109, in setup_databases
    return setup_databases(self.verbosity, self.interactive, **kwargs)
  File "project-path\core_packages\django\test\runner.py", line 299, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "project-path\core_packages\sqlserver_ado\creation.py", line 126, in create_test_db
    self.mark_tests_as_expected_failure(self.connection.features.failing_tests)
  File "project-path\core_packages\sqlserver_ado\creation.py", line 120, in mark_tests_as_expected_failure
    test_case = import_string(test_case_name)
  File "project-path\core_packages\django\utils\module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named aggregation_regress.tests
```

**Comment by adamchainz** [comment]
Hi,

I don't think you're using anything related to this library **django-mysql** and that's something in **django** itself, no? Or is this something that started happening after you installed **django-mysql** ?

**Comment by alexsilva** [comment]
This error only happens in Windows. In Linux does not occur because the library django-mysql is not used.

The library django-mysql need to create the test database. The error occurs at this time.

**Comment by alexsilva** [comment]
No! MSSQL

**Comment by adamchainz** [comment]
No worries!
